#!/usr/bin/env bash
# ============================================================================
# Static export — Alpha Concern
# ----------------------------------------------------------------------------
# Crawls the running PHP dev server and writes a fully static mirror to dist/,
# which is what Vercel serves. Vercel has no PHP runtime, so the live site
# cannot be deployed there directly; this produces a client-ready preview.
#
# LIMITATIONS OF THE EXPORT (by design — it is a snapshot, not the app):
#   • The contact and careers forms POST to /api/*.php and will not work.
#   • The admin panel is deliberately excluded.
#   • Content is frozen at export time; re-run after any CMS change.
#
# Usage:  ./build-static.sh            (dev server must be on :8080)
# ============================================================================

set -euo pipefail

BASE="${BASE:-http://localhost:8080}"

# includes/config.php derives BASE_URL from the request host, so canonical,
# Open Graph and JSON-LD URLs come from whatever Host we send. Crawling with
# the production host stops localhost:8080 being baked into the export.
# (config.php only treats a host as local when it contains localhost/127.0.0.1,
# so this also flips the scheme to https, which is what the deployment uses.)
SITE_HOST="${SITE_HOST:-alpha-constructions.vercel.app}"
CURL=(curl -sf -H "Host: $SITE_HOST")
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="$ROOT/Alpha Concerns/public_html"
OUT="$ROOT/dist"

if ! curl -sf -o /dev/null "$BASE/"; then
  echo "error: no dev server at $BASE — start it first." >&2
  exit 1
fi

echo "==> Clearing $OUT"
rm -rf "$OUT"
mkdir -p "$OUT"

# ---------------------------------------------------------------------------
# Static assets. Copied straight from the web root — same absolute URLs, so
# no rewriting of the HTML is required.
# ---------------------------------------------------------------------------
echo "==> Copying assets"
cp -r "$SRC/assets"  "$OUT/assets"
[ -d "$SRC/uploads" ] && cp -r "$SRC/uploads" "$OUT/uploads"

# ---------------------------------------------------------------------------
# Frame manifest as static JSON. sequence.js tries /api/frames.php first and
# falls back to this when there is no PHP runtime.
# ---------------------------------------------------------------------------
echo "==> Writing frame manifest"
mkdir -p "$OUT/api"
"${CURL[@]}" "$BASE/api/frames.php" -o "$OUT/api/frames.json"
printf '    %s frames\n' "$(grep -o 'ezgif-frame' "$OUT/api/frames.json" | wc -l)"

# ---------------------------------------------------------------------------
# Pages. Detail-page slugs are scraped from the index pages so the list stays
# correct as content is added, rather than being hard-coded here.
# ---------------------------------------------------------------------------
slugs_from() {   # $1 = index path, $2 = url prefix to match
  "${CURL[@]}" "$BASE$1" \
    | grep -oE "href=\"$2/[a-z0-9-]+\"" \
    | sed -E "s|href=\"||; s|\"||" \
    | sort -u
}

PAGES=(/ /about /services /projects /blog /careers /contact /why-us /privacy)
mapfile -t SERVICES < <(slugs_from /services /services)
mapfile -t PROJECTS < <(slugs_from /projects /projects)
mapfile -t POSTS    < <(slugs_from /blog     /blog)
PAGES+=("${SERVICES[@]}" "${PROJECTS[@]}" "${POSTS[@]}")

echo "==> Exporting ${#PAGES[@]} pages"
fail=0
for p in "${PAGES[@]}"; do
  if [ "$p" = "/" ]; then dest="$OUT/index.html"; else dest="$OUT${p}.html"; fi
  mkdir -p "$(dirname "$dest")"
  if "${CURL[@]}" "$BASE$p" -o "$dest"; then
    printf '    %-46s %6s bytes\n' "$p" "$(wc -c < "$dest")"
  else
    printf '    %-46s FAILED\n' "$p" >&2
    fail=1
  fi
done

# 404 page — Vercel serves dist/404.html for unmatched routes automatically.
curl -s -H "Host: $SITE_HOST" "$BASE/__not_found__" -o "$OUT/404.html" || true

# sitemap.xml and robots.txt are generated by the PHP front controller.
"${CURL[@]}" "$BASE/sitemap.xml" -o "$OUT/sitemap.xml" || true
"${CURL[@]}" "$BASE/robots.txt"  -o "$OUT/robots.txt"  || true

echo "==> Done: $(du -sh "$OUT" | cut -f1) in $OUT"
exit $fail
