-- Alpha Concern — real project portfolio
-- Source: Alpha_Concern_Company_Profile.pdf (2026 edition). Replaces the
-- fictional seed data.

DELETE FROM projects;

INSERT INTO projects (title, slug, location, type, status, short_description, full_description,
                      hero_image, key_specs, amenities, seo_title, seo_description,
                      is_published, is_featured, sort_order) VALUES
  ('Zenwish Homes', 'zenwish-homes', 'Surya Darshan Height, Tokha, Kathmandu', 'Residential', 'Completed', 'Twelve residential houses designed, built, and handed over at Surya Darshan Height, Tokha.', 'Phase 1 of the Suryadarshan Residential House Project — twelve of thirty-two houses — designed, built, and handed over to Zenwish Homes at Surya Darshan Height, Tokha. Zenwish Investment Pvt. Ltd. has certified the phase as completed to the required standards of quality, safety, and budget compliance.', '/assets/img/projects/tokha-zenwish.jpg', '{"client":"Zenwish Homes","surface_area":"2,200 Sq.M.","budget":"Rs. 13 Crore","scope":"12 houses completed and handed over"}', '[]', 'Zenwish Homes | Alpha Concern', 'Twelve residential houses designed, built, and handed over at Surya Darshan Height, Tokha.', 1, 1, 1),
  ('Thapathali Showroom', 'thapathali-showroom', 'Thapathali, Kathmandu', 'Commercial', 'Completed', 'Finishing works to a car showroom for Shree T.R. Real Estate and Leasing Company.', 'Complete finishing works to a commercial car showroom at Thapathali, Kathmandu, delivered for Shree T.R. Real Estate and Leasing Company and handed over.', '/assets/img/story/aion-corner.jpg', '{"client":"Shree T.R. Real Estate and Leasing Company","surface_area":"435.39 Sq.M.","budget":"Rs. 4 Crore","scope":"Finishing of car showroom"}', '[]', 'Thapathali Showroom | Alpha Concern', 'Finishing works to a car showroom for Shree T.R. Real Estate and Leasing Company.', 1, 0, 2),
  ('Shera Residence', 'shera-residence', 'Jorpati, Kathmandu', 'Residential', 'Completed', 'Design and building construction of a private residence at Jorpati.', 'Design and building construction of a private residence at Jorpati for Phurba Lama, delivered end to end from drawings through construction and finishing.', '/assets/img/story/residence-brick.jpg', '{"client":"Phurba Lama","land_area":"16 Ana","budget":"Rs. 4 Crore","scope":"Design and building construction"}', '[]', 'Shera Residence | Alpha Concern', 'Design and building construction of a private residence at Jorpati.', 1, 0, 3),
  ('Imperial Apartments', 'imperial-apartment', 'Naxal, Kathmandu', 'Residential', 'Ongoing', 'Finishing works to a fourteen-storey apartment building at Naxal.', 'Finishing works to a fourteen-storey apartment building at Naxal, Kathmandu, for Imperial Apartment Pvt. Ltd. The project is currently at finishing stage.', '/assets/video/imperial-apartment.jpg', '{"client":"Imperial Apartment Pvt. Ltd.","surface_area":"31,678.28 Sq.Ft.","budget":"Rs. 7.5 Crore","scope":"Finishing work of a 14-storey apartment building"}', '[]', 'Imperial Apartments | Alpha Concern', 'Finishing works to a fourteen-storey apartment building at Naxal.', 1, 1, 4),
  ('Quest Pharmaceuticals Research Centre', 'quest-pharmaceuticals', 'Changu, Bhaktapur', 'Institutional', 'Ongoing', 'Construction of a pharmaceutical research centre — R&D and utility building — at Changu, Bhaktapur.', 'Construction of a research centre comprising an R&D building and a utility building for Quest Pharmaceuticals Pvt. Ltd. at Changu, Bhaktapur. The works are running and approximately 50% complete.', '/assets/img/story/commercial-aerial.jpg', '{"client":"Quest Pharmaceuticals Pvt. Ltd.","surface_area":"10,808.6 Sq.M.","budget":"Rs. 38 Crore + Rs. 10 Crore additional","scope":"Research centre \u2014 R&D and utility building","progress":"50% completed"}', '[]', 'Quest Pharmaceuticals Research Centre | Alpha Concern', 'Construction of a pharmaceutical research centre — R&D and utility building — at Changu, Bhaktapur.', 1, 1, 5),
  ('Prajwal Residency', 'prajwal-residency', 'Nagarkot', 'Residential', 'Ongoing', 'Design and building construction of a private residency at Nagarkot.', 'Design and building construction of a private residency for Prajwal KC at Nagarkot, currently under construction.', '/assets/img/hero/services-prajwal-residency.jpg', '{"client":"Prajwal KC","land_area":"2 Ropani","budget":"Rs. 2 Crore","scope":"Design and building construction"}', '[]', 'Prajwal Residency | Alpha Concern', 'Design and building construction of a private residency at Nagarkot.', 1, 0, 6),
  ('Budhanilkantha Heights', 'budhanilkantha-heights', 'Budhanilkantha, Kathmandu', 'Residential', 'Upcoming', 'A seven-storey apartment building for Platinum Real Estate, currently at drawing verification.', 'Design and building construction of a seven-storey apartment building at Budhanilkantha for Platinum Real Estate Pvt. Ltd. The project is currently at drawing verification stage.', '/assets/video/budhanilkantha-heights.jpg', '{"client":"Platinum Real Estate Pvt. Ltd.","building":"7-storey apartment building","boq_amount":"Rs. 45 Crore","status":"Drawing verification"}', '[]', 'Budhanilkantha Heights | Alpha Concern', 'A seven-storey apartment building for Platinum Real Estate, currently at drawing verification.', 1, 1, 7),
  ('Warish Residence', 'warish-residence', 'Greenland', 'Residential', 'Upcoming', 'Design and building construction of a private residence, currently at drawing verification.', 'Design and building construction of the Warish Residence for Warish Dharel at Greenland. The project is currently at drawing verification stage.', '', '{"client":"Warish Dharel","boq_amount":"Rs. 4 Crore","status":"Drawing verification"}', '[]', 'Warish Residence | Alpha Concern', 'Design and building construction of a private residence, currently at drawing verification.', 1, 0, 8);
